version: "3.8" # https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
