version: "3.8" # https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data

  meme_app:
    container_name: smashing_memes_together # Aaaayy
    build:
      dockerfile: gradle_built.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - GITHUB_OAUTH_ID # To be directly passed in from an .env file
      - GITHUB_OAUTH_SECRET # To be directly passed in from an .env file
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-data:
