version: "3.8" # https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  memes_database:
    image: 'postgres:13.1-alpine'
    container_name: memes_db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres-memes:/var/lib/postgresql/data

  memes_spring:
    container_name: memes_api
    build:
      dockerfile: gradle_built.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - memes_database
    environment: # All values are from an .env file, and are either passed in directly or by reference below
      - GITHUB_OAUTH_ID
      - GITHUB_OAUTH_SECRET
      - SPRING_DATASOURCE_URL
      - SPRING_JPA_HIBERNATE_DDL_AUTO
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  memes_react:
    container_name: memes_web
    build:
      context: ./frontend
    ports:
      - "3000:3000"
#   depends_on:
#     - memes_spring

volumes:
  postgres-memes:
