version: "3.8" # https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data

  meme_app:
    container_name: smashing_memes_together # Aaaayy
    build:
      dockerfile: gradle_built.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment: # All values are from an .env file, and are either passed in directly or by reference below
      - GITHUB_OAUTH_ID
      - GITHUB_OAUTH_SECRET
      - SPRING_DATASOURCE_URL
      - SPRING_JPA_HIBERNATE_DDL_AUTO
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-data:
