spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_OAUTH_ID}
            clientSecret: ${GITHUB_OAUTH_SECRET}
  jpa:
    show-sql: true
    generate-ddl: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver # Inclusion ensures the JUnit test passes https://stackoverflow.com/a/31781524